### ISSUE TITLE
cut down on sideboard cards?

### ISSUE THREAD

**Issue by tooomm** [april/decklist#32]
Would it make sense to cut down the maximum entries in the sideboard to 15 different card names?
As that is the maximum lines available and all further entries mess the judge box up, basically rendering all list unusable or unreadable:
![untitled](https://user-images.githubusercontent.com/9874850/33618985-4dab15e0-d9e4-11e7-82e2-b7057867d48c.png)

I think cutting down to 15 entries (no matter how much cards there are in total) keeps readability at least.
Same could apply to the decklist and the number of available lines for card entries, too.

There should be an appropriate (and additional) warning for sure if not all cards make it to the list!

**Comment by Nightfirecat** [comment]
Should probably also be done for main deck; it has the same rendering issue after enough unique cards are entered.

**Comment by tooomm** [comment]
Are there enough lines for a commander deck by the way?
I mean there are official tournaments as well, right? 😆

**Comment by Nightfirecat** [comment]
There are not, though I don't know what kind of registration sheets they use.

**Comment by Fryyyyy** [comment]
My fork currently supports spilling decklists over multiple pages, so feel free to steal the code (if it's still vaguely sync'ed with upstream)

**Comment by Nightfirecat** [comment]
This is fixed in #42.

**Comment by tooomm** [comment]
Does your PR also cut down for the main deck? @Nightfirecat 
Or supports multiple pages as @Fryyyyy with his fork?

**Comment by Nightfirecat** [comment]
I believe I did go ahead and limit both maindeck and sideboard rendering to the number of available slots. I didn't write any logic for page looping.
