### ISSUE TITLE
add clickable website link to repo and/or readme

### ISSUE THREAD

**Issue by tooomm** [april/decklist#37]

**Comment by Nightfirecat** [comment]
There's one in the footer already.


![decklist.org footer with GitHub link circled in red](https://user-images.githubusercontent.com/2199511/35990070-d2c69d82-0cfa-11e8-9f45-1d0af309873c.png)

**Comment by tooomm** [comment]
The other way around, I'm speaking about the repo here at GitHub itself.
It should contain a clickable link to the decklist.org page.

**Comment by Nightfirecat** [comment]
Oh, gotcha. 🙃

**Comment by april** [comment]
Done!  😀

**Comment by tooomm** [comment]
Cool, thanks!
