### ISSUE TITLE
Ignore trailing spaces after card names

### ISSUE THREAD

**Issue by richardneal** [april/decklist#38]
I've run into the issue when copy/pasting from other sources (especially PDF) that trailing spaces cause card names to not be recognized – it'd be great if they could be ignored.

**Comment by Nightfirecat** [comment]
Implemented this #39; you can test it here: https://nightfirecat.github.io/decklist/?deckmain=1%20Tarmogoyf%0A1%20Tarmogoyf%20

**Comment by richardneal** [comment]
Works great, thanks for the quick implementation!
