### ISSUE TITLE
enable/run from gh pages

### ISSUE THREAD

**Issue by tooomm** [april/decklist#44]

**Comment by Nightfirecat** [comment]
:tada: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
cc: @april

**Comment by april** [comment]
So, I've gone ahead and made `gh-pages` the default branch. The website is live here:
https://april.github.io/decklist/

That said, one of the issues with converting to a pure gh-pages thing is that it doesn't support AAAA/IPv6, like my website does. That's probably okay, but not 100% sure.

**Comment by Nightfirecat** [comment]
I think that's up to you as the site maintainer. If you'd prefer to use your web host for whatever HTTP features it offers, that's fine--I don't really have any say in that discussion. Hosting from GitHub pages to let GitHub worry about handling the hosting is at least an option now though. /shrug

**Comment by april** [comment]
Closing for now. Once GitHub pages works with IPv6, I'll switch to using it exclusively. For now, we can see changes before they're pushed live.  :)
